print('-='*20)
print(f'{"CONVERSOR DE METROS" :^40}')
print('-='*20)
metragem =int(input('Digite um número em metros: '))
print(f'o valor digitado em kilometros é {metragem / 1000}km ,\n em  centimetros {metragem * 100}cm \ne milimetros {metragem * 1000} mm')